# Basic Math

## imports

In [55]:
from numpy import arange, array

## Exercise 1


In [56]:
u = array([1.0, 1, 2, 3, 5, 8])
v = array([[1.0], [1], [2], [3], [5], [8]])
x = array([[1.0, 0], [0, 1]])
y = array([[1.0, 2], [3, 4]])
z = array([[1.0, 2, 1, 2], [3, 4, 3, 4], [1, 2, 1, 3]])
w = array([[1.0, 0, 1, 0], [0, 1, 0, 1], [1, 2, 1, 2], [3, 4, 3, 4]])

In [57]:
print("u+v.T:")
u + v.T

u+v.T:


array([[ 2.,  2.,  4.,  6., 10., 16.]])

In [58]:
print("v+u:")
v + u

v+u:


array([[ 2.,  2.,  3.,  4.,  6.,  9.],
       [ 2.,  2.,  3.,  4.,  6.,  9.],
       [ 3.,  3.,  4.,  5.,  7., 10.],
       [ 4.,  4.,  5.,  6.,  8., 11.],
       [ 6.,  6.,  7.,  8., 10., 13.],
       [ 9.,  9., 10., 11., 13., 16.]])

In [59]:
print("v+u.T :")
v + u.T

v+u.T :


array([[ 2.,  2.,  3.,  4.,  6.,  9.],
       [ 2.,  2.,  3.,  4.,  6.,  9.],
       [ 3.,  3.,  4.,  5.,  7., 10.],
       [ 4.,  4.,  5.,  6.,  8., 11.],
       [ 6.,  6.,  7.,  8., 10., 13.],
       [ 9.,  9., 10., 11., 13., 16.]])

In [60]:
u.shape = 1, 6
u

array([[1., 1., 2., 3., 5., 8.]])

In [61]:
print("v@u:")
v @ u

v@u:


array([[ 1.,  1.,  2.,  3.,  5.,  8.],
       [ 1.,  1.,  2.,  3.,  5.,  8.],
       [ 2.,  2.,  4.,  6., 10., 16.],
       [ 3.,  3.,  6.,  9., 15., 24.],
       [ 5.,  5., 10., 15., 25., 40.],
       [ 8.,  8., 16., 24., 40., 64.]])

In [62]:
print("u@v:")
u @ v

u@v:


array([[104.]])

In [63]:
print("x@y:")
x @ y

x@y:


array([[1., 2.],
       [3., 4.]])

## Exercise 2


In [64]:
u = array([1.0, 1, 2, 3, 5, 8])
v = array([[1.0], [1], [2], [3], [5], [8]])
x = array([[1.0, 0], [0, 1]])
y = array([[1.0, 2], [3, 4]])
z = array([[1.0, 2, 1, 2], [3, 4, 3, 4], [1, 2, 1, 3]])
w = array([[1.0, 0, 1, 0], [0, 1, 0, 1], [1, 2, 1, 2], [3, 4, 3, 4]])
a = array([3.0, 2])
b = array([[3.0], [2]])
c = array([3.0, 2, 1, 0])
d = array([[3.0], [2], [1], [0]])
print("u+b:")
print(u + b)
print("u+d:")
print(u + d)
print("v+a:")
print(v + a)
print("v+c:")
print(v + c)
print("x+a:")
print(x + a)
print("x+b:")
print(x + b)
print("y+a:")
print(y + a)
print("y+b:")
print(y + b)
print("z+c:")
print(z + c)
print("w+c:")
print(w + c)
print("w+d:")
print(w + d)

u+b:
[[ 4.  4.  5.  6.  8. 11.]
 [ 3.  3.  4.  5.  7. 10.]]
u+d:
[[ 4.  4.  5.  6.  8. 11.]
 [ 3.  3.  4.  5.  7. 10.]
 [ 2.  2.  3.  4.  6.  9.]
 [ 1.  1.  2.  3.  5.  8.]]
v+a:
[[ 4.  3.]
 [ 4.  3.]
 [ 5.  4.]
 [ 6.  5.]
 [ 8.  7.]
 [11. 10.]]
v+c:
[[ 4.  3.  2.  1.]
 [ 4.  3.  2.  1.]
 [ 5.  4.  3.  2.]
 [ 6.  5.  4.  3.]
 [ 8.  7.  6.  5.]
 [11. 10.  9.  8.]]
x+a:
[[4. 2.]
 [3. 3.]]
x+b:
[[4. 3.]
 [2. 3.]]
y+a:
[[4. 4.]
 [6. 6.]]
y+b:
[[4. 5.]
 [5. 6.]]
z+c:
[[4. 4. 2. 2.]
 [6. 6. 4. 4.]
 [4. 4. 2. 3.]]
w+c:
[[4. 2. 2. 0.]
 [3. 3. 1. 1.]
 [4. 4. 2. 2.]
 [6. 6. 4. 4.]]
w+d:
[[4. 3. 4. 3.]
 [2. 3. 2. 3.]
 [2. 3. 2. 3.]
 [3. 4. 3. 4.]]


## Exercise 3


In [65]:
print("x/1.0:")
print(x / 1.0)
print("1.0/x:")
print(1.0 / x)

x/1.0:
[[1. 0.]
 [0. 1.]]
1.0/x:
[[ 1. inf]
 [inf  1.]]


C:\Users\kevin\AppData\Local\Temp/ipykernel_36968/1622983613.py:4: RuntimeWarning: divide by zero encountered in true_divide
  print(1.0 / x)


## Exercise 4

These are the same since these are jsut element-by-element.  The bottom shows
how to do the same using linear algebra.

In [66]:
(x + y) ** 2

array([[ 4.,  4.],
       [ 9., 25.]])

In [67]:
x ** 2 + x * y + y * x + y ** 2

array([[ 4.,  4.],
       [ 9., 25.]])

In [68]:
(x + y) @ (x + y)

array([[10., 14.],
       [21., 31.]])

In [69]:
x @ x + x @ y + y @ x + y @ y

array([[10., 14.],
       [21., 31.]])

## Exercise 5


In [70]:
x ** 2 + 2 * x * y + y ** 2

array([[ 4.,  4.],
       [ 9., 25.]])

In [71]:
x @ x + 2 * x @ y + y @ y

array([[10., 14.],
       [21., 31.]])

## Exercise 6


In [72]:
a = arange(3.0)
b = a
c = a

In [73]:
print("a*b + a*c:")
a * b + a * c

a*b + a*c:


array([0., 2., 8.])

In [74]:
print("a*b + c:")
a * b + c

a*b + c:


array([0., 2., 6.])

In [75]:
print("a*(b+c):")
a * (b + c)

a*(b+c):


array([0., 2., 8.])

Also works for `@`

In [76]:
print("a*b + a*c:")
a @ b + a @ c

a*b + a*c:


10.0

In [77]:
print("a*b + c:")
a @ b + c

a*b + c:


array([5., 6., 7.])

In [78]:
print("a*(b+c):")
a @ (b + c)

a*(b+c):


10.0

## Exercise 7

If `x` is array, `y` must be broadcastable with `x`, 

`w` must be broadcastable with (`x**y`)

`z` must be broadcastable with (`(x**y)*w`)


## Exercise 10


In [79]:
print("-2**4:")
-(2 ** 4)

-2**4:


-16

In [80]:
print("(-2)**4:")
(-2) ** 4

(-2)**4:


16

In [81]:
print("-2*-2*-2*-2:")
-2 * -2 * -2 * -2

-2*-2*-2*-2:


16