# Arrays and Matrices

## imports

In [1]:
import numpy as np
from numpy import array, matrix, shape

## Exercise 1

In [2]:
u = array([1.0, 1, 2, 3, 5, 8])
u

array([1., 1., 2., 3., 5., 8.])

In [3]:
v = array([[1.0], [1], [2], [3], [5], [8]])
v

array([[1.],
       [1.],
       [2.],
       [3.],
       [5.],
       [8.]])

In [4]:
x = array([[1.0, 0], [0, 1]])
x

array([[1., 0.],
       [0., 1.]])

In [5]:
y = array([[1.0, 2], [3, 4]])
y

array([[1., 2.],
       [3., 4.]])

In [6]:
z = array([[1.0, 2, 1, 2], [3, 4, 3, 4], [1, 2, 1, 3]])
z

array([[1., 2., 1., 2.],
       [3., 4., 3., 4.],
       [1., 2., 1., 3.]])

In [7]:
w = array([[1.0, 0, 1, 0], [0, 1, 0, 1], [1, 2, 1, 2], [3, 4, 3, 4]])
w

array([[1., 0., 1., 0.],
       [0., 1., 0., 1.],
       [1., 2., 1., 2.],
       [3., 4., 3., 4.]])

## Exercise 2

In [8]:
print("w[:2,:2]:")
print(w[:2, :2])

w[:2,:2]:
[[1. 0.]
 [0. 1.]]


## Exercise 3

In [9]:
print("w[:,:2]:")
print(w[:, :2])
print("w[:,-2:]:")
print(w[:, -2:])

w[:,:2]:
[[1. 0.]
 [0. 1.]
 [1. 2.]
 [3. 4.]]
w[:,-2:]:
[[1. 0.]
 [0. 1.]
 [1. 2.]
 [3. 4.]]


## Exercise 4

In [10]:
print("z[:2,:2]:")
print(z[:2, :2])
print("z[:2,2:]:")
print(z[:2, 2:])

z[:2,:2]:
[[1. 2.]
 [3. 4.]]
z[:2,2:]:
[[1. 2.]
 [3. 4.]]


# Exercise 5

In [11]:
y = array([[1.0, -2], [-3, 4]], dtype=float)
y

array([[ 1., -2.],
       [-3.,  4.]])

In [12]:
y = array([[1.0, -2], [-3, 4]], dtype=np.float64)
y

array([[ 1., -2.],
       [-3.,  4.]])

In [13]:
y = array([[1.0, -2], [-3, 4]], dtype=np.int32)
y

array([[ 1, -2],
       [-3,  4]])

In [14]:
y = array([[1.0, -2], [-3, 4]], dtype=np.uint32)
y

array([[         1, 4294967294],
       [4294967293,          4]], dtype=uint32)

In [15]:
y = array([[1.0, -2], [-3, 4]], dtype=np.complex128)
y

array([[ 1.+0.j, -2.+0.j],
       [-3.+0.j,  4.+0.j]])

In [16]:
y = array([[1.0, -2], [-3, 4]], copy=False)
y

array([[ 1., -2.],
       [-3.,  4.]])

In [17]:
y = array([[1.0, -2], [-3, 4]], ndmin=3)
y

array([[[ 1., -2.],
        [-3.,  4.]]])

In [18]:
print("shape(y):")
print(shape(y))

shape(y):
(1, 2, 2)


In [19]:
y = array([[1.0, -2], [-3, 4]], ndmin=4)
y

array([[[[ 1., -2.],
         [-3.,  4.]]]])

In [20]:
print("shape(y):")
print(shape(y))

shape(y):
(1, 1, 2, 2)
