In [1]:
import numpy as np
from numpy.random import default_rng

SEED = int(10 ** 13 * np.pi)
SEED

31415926535897

# Exercise 1

In [2]:
gen = default_rng(SEED)
gen.standard_normal(10)

array([-1.12087147, -1.47693615,  0.36959407,  1.52005265,  0.35310357,
       -1.13555464, -1.63611594, -0.07295773, -1.06056688, -1.54483307])

In [3]:
gen.normal(size=10)

array([ 0.34641686,  0.26624936, -0.04157256, -0.15597542, -0.71199179,
        1.42614287,  0.59999017, -1.12868585,  2.45538905, -0.11073076])

In [4]:
# Parameters are mean and scale, i.e., stdandard deviation
gen.normal(3, 3, size=10)

array([ 5.44821074,  4.91389961, -2.17536119,  1.66811946, -0.71530719,
        4.8467949 ,  1.73302988,  4.62500782,  0.59214696, -2.05970507])

In [5]:
gen.random(10)

array([0.50589382, 0.74331811, 0.84894578, 0.78031166, 0.19871486,
       0.75741724, 0.791959  , 0.70253428, 0.087387  , 0.8514891 ])

In [6]:
gen.uniform(0, 1, size=10)

array([0.30078457, 0.98701999, 0.76811124, 0.29045321, 0.45955654,
       0.44255291, 0.14077977, 0.82417729, 0.64695318, 0.91361973])

In [7]:
gen.uniform(-1, 1, size=10)

array([ 0.60869667, -0.21666756,  0.01584656,  0.73490492,  0.66487271,
        0.78096438,  0.16203263, -0.64234756,  0.27588701,  0.79404433])

In [8]:
gen.gamma(1, 2, size=10)

array([0.46181776, 3.75753353, 5.77428015, 4.9774197 , 0.62712234,
       0.08553175, 0.28261634, 3.67809018, 1.76750853, 1.7047245 ])

In [9]:
# mu, sigma
gen.lognormal(0.8, 0.2, size=10)

array([2.13230629, 2.44962117, 1.99838733, 2.09064797, 1.88840364,
       1.82857597, 1.92078925, 2.3497724 , 2.15522394, 2.43655622])

# Exercise 2

In [10]:
gen = default_rng(SEED)
first = gen.integers(0, 11, size=10)
first

array([ 9,  3, 10,  4,  9,  1,  1,  2,  0,  7], dtype=int64)

In [11]:
gen = default_rng(SEED)
second = gen.integers(0, 11, size=10)
second

array([ 9,  3, 10,  4,  9,  1,  1,  2,  0,  7], dtype=int64)

In [12]:
first - second

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int64)

# Exercise 3

In [13]:
sigma = np.array([[1, -0.5], [-0.5, 1]])
mvn = gen.multivariate_normal([0, 0], sigma, size=10000)
cov = np.cov(mvn.T)
cov

array([[ 0.99797994, -0.51077754],
       [-0.51077754,  1.02748402]])

In [14]:
cov - sigma

array([[-0.00202006, -0.01077754],
       [-0.01077754,  0.02748402]])

# Exercise 4

In [15]:
from numpy.random import PCG64, Generator, SeedSequence

ss = SeedSequence(SEED)
pcg = PCG64(ss)
gen = Generator(pcg)
pcg5 = gen.random(5)
pcg5

array([0.33966653, 0.3724006 , 0.10559387, 0.23378977, 0.65711565])

In [16]:
gen = default_rng(SEED)
gen.random(5)

array([0.33966653, 0.3724006 , 0.10559387, 0.23378977, 0.65711565])

In [17]:
from numpy.random import Philox

ss = SeedSequence(SEED)
philox = Philox(ss)
philox_gen = Generator(philox)

In [18]:
philox5 = philox_gen.random(5)
philox5

array([0.68144335, 0.17674075, 0.24246577, 0.21657299, 0.90329184])

In [19]:
pcg5 - philox5

array([-0.34177682,  0.19565985, -0.1368719 ,  0.01721678, -0.24617619])

# Exercise 5

In [20]:
ss = SeedSequence(SEED)
children = ss.spawn(2)
gen = default_rng(ss)
child_gen1 = default_rng(children[0])
child_gen2 = default_rng(children[1])

In [21]:
# No spawn key
ss

SeedSequence(
    entropy=31415926535897,
    n_children_spawned=2,
)

In [22]:
# See the spawn key
children[0]

SeedSequence(
    entropy=31415926535897,
    spawn_key=(0,),
)

In [23]:
# Different spawn key
children[1]

SeedSequence(
    entropy=31415926535897,
    spawn_key=(1,),
)

In [24]:
gen.random(5)

array([0.33966653, 0.3724006 , 0.10559387, 0.23378977, 0.65711565])

In [25]:
child_gen1.random(5)

array([0.10906813, 0.91112154, 0.80902991, 0.08099842, 0.82565723])

In [26]:
child_gen2.random(5)

array([0.09535427, 0.69865339, 0.95871024, 0.97860932, 0.59972837])

# Exercise 6

In [30]:
np.random.seed(int(10 ** 5 * np.pi))
np.random.random_sample(5)

array([0.81792331, 0.5510463 , 0.41977535, 0.09869185, 0.81102075])

In [31]:
np.random.seed(int(10 ** 5 * np.pi))
np.random.random_sample(5)

array([0.81792331, 0.5510463 , 0.41977535, 0.09869185, 0.81102075])

# Exercise 7

In [32]:
state = np.random.get_state()
np.random.random_sample(5)

array([0.9673564 , 0.09820669, 0.80186037, 0.60490212, 0.58476881])

In [33]:
np.random.set_state(state)
np.random.random_sample(5)

array([0.9673564 , 0.09820669, 0.80186037, 0.60490212, 0.58476881])