# Array Functions


In [1]:
from numpy import (
    arange,
    array,
    diag,
    dot,
    eye,
    hstack,
    kron,
    prod,
    reshape,
    tile,
    trace,
    vstack,
)
from numpy.linalg import cholesky, det, eig, eigvals, inv, lstsq, matrix_rank
from numpy.random import randn

## Exercise 1


In [2]:
x = arange(12.0)
x.shape = 2, 6
x.shape = 3, 4
x.shape = 4, 3
x.shape = 6, 2
x.shape = 2, 2, 3
x.shape = 12

## Exercise 2


In [3]:
x = reshape(arange(12.0), (4, 3))
x

array([[ 0.,  1.,  2.],
       [ 3.,  4.,  5.],
       [ 6.,  7.,  8.],
       [ 9., 10., 11.]])

In [4]:
print("x.flatten()[1::2]:")
x.flatten()[1::2]

x.flatten()[1::2]:


array([ 1.,  3.,  5.,  7.,  9., 11.])

In [5]:
print("x.ravel()[1::2]:")
x.ravel()[1::2]

x.ravel()[1::2]:


array([ 1.,  3.,  5.,  7.,  9., 11.])

In [6]:
print("x.flat[1::2]:")
x.flat[1::2]

x.flat[1::2]:


array([ 1.,  3.,  5.,  7.,  9., 11.])

## Exercise 3


In [7]:
x = randn(2, 2)
y = randn(1, 1)
z = randn(3, 2)
pt1 = hstack((x, tile(y, (2, 3))))
pt2 = vstack((z.T, tile(y, (1, 3))))
pt3 = hstack((z, pt2))
final = vstack((pt1, pt3))
final

array([[-0.70320789,  0.70891108,  1.33492825,  1.33492825,  1.33492825],
       [ 2.26997202, -0.52297885,  1.33492825,  1.33492825,  1.33492825],
       [ 0.1361734 , -0.41282196,  0.1361734 ,  0.62447801, -0.17889649],
       [ 0.62447801, -0.45030111, -0.41282196, -0.45030111, -0.76464353],
       [-0.17889649, -0.76464353,  1.33492825,  1.33492825,  1.33492825]])

## Exercise 4


In [8]:
x = reshape(arange(12.0), (2, 2, 3))
print("x.squeeze():")
x.squeeze()

x.squeeze():


array([[[ 0.,  1.,  2.],
        [ 3.,  4.,  5.]],

       [[ 6.,  7.,  8.],
        [ 9., 10., 11.]]])

## Exercise 5


In [9]:
y = array([[2, 0.5], [0.5, 4]])
z = diag(diag(y))
z

array([[2., 0.],
       [0., 4.]])

## Exercise 6


In [10]:
z = cholesky(y)
z

array([[1.41421356, 0.        ],
       [0.35355339, 1.96850197]])

In [11]:
print("dot(z,z.T):")
dot(z, z.T)

dot(z,z.T):


array([[2. , 0.5],
       [0.5, 4. ]])

## Exercise 7


In [12]:
print("trace(y):")
trace(y)

trace(y):


6.0

In [13]:
D = eigvals(y)
print("sum(D):")
sum(D)

sum(D):


6.0

## Exercise 7b


In [14]:
print("det(y):")
det(y)

det(y):


7.749999999999999

In [15]:
print("prod(D):")
prod(D)

prod(D):


7.75

## Exercise 8


In [16]:
print("inv(y):")
inv(y)

inv(y):


array([[ 0.51612903, -0.06451613],
       [-0.06451613,  0.25806452]])

In [17]:
(D, V) = eig(y)
D = 1 / D
print("dot(dot(V,diag(D)),V.T):")
dot(dot(V, diag(D)), V.T)

dot(dot(V,diag(D)),V.T):


array([[ 0.51612903, -0.06451613],
       [-0.06451613,  0.25806452]])

## Exercise 9


In [18]:
x = randn(100, 2)
e = randn(100, 1)
B = array([[1], [0.5]])
y = dot(x, B) + e
out = lstsq(x, y, rcond=None)
estimate = out[0]
estimate

C:\Users\kevin\AppData\Local\Temp/ipykernel_46664/3295548839.py:5: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  out = lstsq(x,y)


array([[0.8824831 ],
       [0.44583898]])

## Exercise 10


In [19]:
y = array([[5, -1.5, -3.5], [-1.5, 2, -0.5], [-3.5, -0.5, 4]])
D = eigvals(y)
print("matrix_rank(y):")
matrix_rank(y)

matrix_rank(y):


2

In [20]:
print("det(y):")
det(y)

det(y):


-5.162537064506973e-15

## Exercise 11


In [21]:
x = randn(100, 2)
SigmaX = dot(x.T, x) / 100
print("kron(eye(2),SigmaX):")
kron(eye(2), SigmaX)

kron(eye(2),SigmaX):


array([[1.00235481, 0.01544071, 0.        , 0.        ],
       [0.01544071, 0.95511212, 0.        , 0.        ],
       [0.        , 0.        , 1.00235481, 0.01544071],
       [0.        , 0.        , 0.01544071, 0.95511212]])